apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secureguard-drift.fullname" . }}-secret
  labels:
    {{- include "secureguard-drift.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | default "" | b64enc | quote }}
